FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y	g++ \
						cmake \
						make \
						git \
						pkg-config \
						ninja-build \
						gnome-desktop-testing \
						libasound2-dev \
						libpulse-dev \
						libaudio-dev \
						libjack-dev \
						libsndio-dev \
						libx11-dev \
						libxext-dev \
						libxrandr-dev \
						libxcursor-dev \
						libxfixes-dev \
						libxi-dev \
						libxss-dev \
						libxkbcommon-dev \
						libdrm-dev \
						libgbm-dev \
						libgl1-mesa-dev \
						libgles2-mesa-dev \
						libegl1-mesa-dev \
						libdbus-1-dev \
						libibus-1.0-dev \
						libudev-dev \
						fcitx-libs-dev
