name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  linux:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=install ..
        make install

    - name: Set test-data permisions
      run: |
        cd bin/unit-tests
        chmod 666 test-data/*/*

    - name: general-play-man-unit-tests

      run: |
        cd bin/unit-tests
        ./general-play-man-unit-tests

    - name: gameboy-unit-tests
      run: |
        cd bin/unit-tests
        ./gameboy/gameboy-unit-tests

    - name: utility-unit-tests
      run: |
        cd bin/unit-tests
        ./utility/utility-unit-tests


  macos:

    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=install ..
        make install

    - name: Set test-data permisions
      run: |
        cd bin/unit-tests
        chmod 666 test-data/*/*
  
    - name: general-play-man-unit-tests
      run: |
        cd bin/unit-tests
        ./general-play-man-unit-tests

    - name: gameboy-unit-tests
      run: |
        cd bin/unit-tests
        ./gameboy/gameboy-unit-tests

    - name: utility-unit-tests
      run: |
        cd bin/unit-tests
        ./utility/utility-unit-tests


  windows:

    runs-on: windows-latest
    timeout-minutes: 10
  
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build
      run: |
        cmake -B build -G "MinGW Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=install
        make -C build install

    - name: Set test-data permisions
      run: |
        cd bin/unit-tests
        chmod 666 test-data/*/*

    - name: general-play-man-unit-tests
      run: |
        cd bin/unit-tests
        ./general-play-man-unit-tests

    - name: gameboy-unit-tests
      run: |
        cd bin/unit-tests
        ./gameboy/gameboy-unit-tests

    - name: utility-unit-tests
      run: |
        cd bin/unit-tests
        ./utility/utility-unit-tests
